version: '3'

services:
  app:
    build: .
    image: crud-nest-img:latest
    deploy:
      resources: 
        limits:
          memory: 1024M
        reservations:
          memory: 512M
    tty: true
    command:  npm run start:dev
    ports:
      - '3003:3000'
    depends_on:
     - mysqldb
    volumes:
      - .:/home/app/node_docker

  mysqldb:
   image: mysql5-img:latest
   command: --default-authentication-plugin=mysql_native_password
   restart: always
   environment:
      MYSQL_ROOT_PASSWORD: senha
   ports:
    - '3336:3306'
   volumes:
    - volume-db-fm:/var/lib/mysql
volumes:
   volume-db-fm:
    external: true 